### ISSUE TITLE
Error that email is in use, but that's not possible

### ISSUE THREAD

**Issue by thibaultmol** [loomchild/sojourner-web#126]
Hi, I just got this error while trying to register on the site
![Screenshot 2023-02-01 16 39 46](https://user-images.githubusercontent.com/1010226/216089822-3e3690c5-efb2-436b-8583-5539adae4211.png)
Even though the email I signed up with is unique (I just created it using SimpleLogin).
So I'm guessing it's more like a ban on using .link TLD's?

**Comment by loomchild** [comment]
Hi, thanks for reporting.

Yes, it's possibly a ban. I am simply using Firebase auth, so they might be blocking some domains. Weird that the error message is this, but again, I am simply displaying it.

**Comment by loomchild** [comment]
Actually, I was able to register to Sojourner using email generated via SimpleLogin. Can you try another email, perhaps it's really taken? Or perhaps there was an error during first registration and the account was finally created?

**Comment by thibaultmol** [comment]
Ok so seems like it did actually make the account, it just threw that error. 

Actually actually: maybe I clicked the register button twice or something. I can't recreate it.

I would like to note though that this implementation of the material design notifications at the bottom; have the problem that newer notifications don't go over it. Like if I logout accidentally and then log back in. the login message won't appear until the 'successful logout' notification has gone away. I think it might be better if it were to show the 'successful login' above the 'logout'. This is an example. But I meant that newer notifications should display over old notifications
