### ISSUE TITLE
Show bookmarks as actual calendar 

### ISSUE THREAD

**Issue by thibaultmol** [loomchild/sojourner-web#127]
I kinda wish the bookmarks page would show the events as an actual calendar interface. Where you can see each event and it's length. So you can more easily see how much 'free space' you have between each of the events

**Comment by loomchild** [comment]
That would be pretty hard to for huge event like FOSDEM. I don't think I'll have time to do that in foreseeable future because it requires huge amount of UI/UX work. I will close it but of it keeps coming back, I'll try to look into this.
