### ISSUE TITLE
Persistence on iOS12 Safari not working

### ISSUE THREAD

**Issue by domrim** [loomchild/sojourner-web#13]
Since iOS 11 Safari has an Storage API.
But the persistence Feature does not work.
Any idea why?
For more details about the implementation: https://webkit.org/blog/8124/introducing-storage-access-api/

**Comment by loomchild** [comment]
No idea, I don't have a Mac and iOS device to debug right now. Feel free to provide error messages. IMHO there's simply no StorageManager class in Safari (https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist).

Please use Log In functionality to avoid losing data. Also from what I found iOS shouldn't delete the data, even without indicating it as persistent (l can't give 100% guarantee).

See https://github.com/loomchild/sojourner-web/issues/11 for more details.

Regarding the link - I don't think it's relevant as it describes privacy feature, not persistent storage.
