### ISSUE TITLE
Consider shorter domain name

### ISSUE THREAD

**Issue by loomchild** [loomchild/sojourner-web#136]
Probably also rename this repo.

**Comment by digitalica** [comment]
personally i dont care about domain name. my browser will remember it ;-) if anything, i would prefer sojourner be in front, not fosdem like fosdem.org. That would help to access faster ;-)

for me, domain name is ok.

**Comment by loomchild** [comment]
Thanks for your feedback :)

Just `sojourner.rocks` currently works. The reason for `fosdem.` subdomain, is that it was used for other conferences in the past. I also wanted to indicate that the webapp is related to FOSDEM.

I was considering shortening the name, since some people, including me:), find the word difficult to spell and write. On the other hand, I now have a nice story behind the name (see About page), so I think I'll keep it:)
