### ISSUE TITLE
FOSDEM main tracks not showing?

### ISSUE THREAD

**Issue by thibaultmol** [loomchild/sojourner-web#140]
![image](https://github.com/loomchild/sojourner-web/assets/1010226/2e10d641-a51b-47cf-a73f-b4747d7128b6)

**Comment by loomchild** [comment]
Hey, I see there are 2 main tracks, same as on the foadem.org site: https://fosdem.org/2024/schedule/

Do you think something is missing?

**Comment by thibaultmol** [comment]
oh sorry, it updated. It say 0 tracks earlier. right before I had refreshed and taken that screenshot XD
it's okay now yeah. cool

**Comment by loomchild** [comment]
Hehe, yes, it refreshes itself in the background. But the organizers really waited until the last minute before announcing the main tracks this year ;)
