### ISSUE TITLE
"What's happening" screen

### ISSUE THREAD

**Issue by ksurent** [loomchild/sojourner-web#17]
First of all, thanks for the app! I've used it for FOSDEM'20 and found it super convenient. I will likely use it in '21.

This year, several times I found myself wanting a list of talks that are either happening right now or are about to start (e.g. I wasn't able to get into the room I wanted or I lost interest in the talk I was at). I think it'd be handy to have a separate screen for this. What do you think?

**Comment by loomchild** [comment]
Thanks!

Yeah, definitely something like that would be nice, as I was in the same situation at FOSDEM many times. My idea would be to automatically scroll to the currently happening events on Bookmark list. 

In the past I also had a all-events screen, but with 817 events it was hard to manage. 

Your idea of having a screen showing currently happening events (perhaps filtering-out or graying-out full rooms) sounds interesting! Will keep you posted.

**Comment by loomchild** [comment]
Done via Live page: https://fosdem.sojourner.rocks/live. List is filtered to show events starting in 10 minutes or happening now. Bookmarked events are shown first.
