### ISSUE TITLE
Add a link to the video stream

### ISSUE THREAD

**Issue by ksurent** [loomchild/sojourner-web#18]
It'd be convenient to have the talk details screen to have a link to the video stream.

**Comment by loomchild** [comment]
Hm, in fact it should be there in the links section. I can't check it anymore, but I am pretty sure I saw it in the past. Also, links to the talk videos are automatically added to each talk (by FOSDEM system).

**Comment by loomchild** [comment]
Now the videos and live streams are visible directly as a thumbnail.
