### ISSUE TITLE
Display sessions in local timezones?

### ISSUE THREAD

**Issue by Humancell** [loomchild/sojourner-web#68]
With the conference being completely virtual, and people attending from around the world, it would be great to display the session times in the browser/local timezone. Another option would be to allow the user to select the timezone.

**Comment by loomchild** [comment]
You are right! Sorry, I missed your ticket somehow, will try to fix it today.

**Comment by loomchild** [comment]
Should be showing times in local time zone (I haven't changed the days). 

Please let me know if it works and re-open if needed. (you may need to force refresh page to see the change, I am experiencing some unrelated issues with service worker updates)

**Comment by Humancell** [comment]
It worked great!  Nice app, and thank you so much for creating it!

**Comment by loomchild** [comment]
Thanks for using!
