### ISSUE TITLE
Links to uploaded videos

### ISSUE THREAD

**Issue by abitrolly** [loomchild/sojourner-web#73]
I missed some talks that I would like to watch. I know they will be eventually uploaded to https://video.fosdem.org/2021/stands/ but instead of hunting the videos there, it would be convenient just to keep the event page open until they are ready. Is it possible to add info about the videos to the web view?

**Comment by loomchild** [comment]
Yes, for sure, I didn't intend to stop the Sojourner app after the conference. The videos from all talks will be available to watch as soon as they are published, similar to last year's edition: https://2020.fosdem.sojourner.rocks/

**Comment by abitrolly** [comment]
Is there a way to show a message that video is being processed and will appear right there as soon as speakers review it?

**Comment by loomchild** [comment]
The video will appear in Sojourner as soon as it lands in Pentabarf, a FOSDEM conference planning software. Usually, it's quite fast so I am not convinced if adding a specific message is necessary. FOSDEM staff will certainly send a message once videos are ready, and I will also share it.

**Comment by loomchild** [comment]
FYI: I saw that many videos are already available in Sojourner (without any changes on my side).
