### ISSUE TITLE
Share bookmarks

### ISSUE THREAD

**Issue by loomchild** [loomchild/sojourner-web#77]
Generate a link to list of my bookmarks, with IDs embedded. The Receiver can also favourite them if they want. 

I can promote this feature by sharing my bookmarks from last year as to be watched.

**Comment by loomchild** [comment]
Technically could be a ... button in bookmarks tab.

**Comment by mrchrisadams** [comment]
I would _love_ this - I was literally looking for this feature when creating my list of bookmarked sessions for FOSDEM today, and would love to find a way to share it.

**A possible stopgap**

However, just being able to download the bookmarks as a JSON file would be a really helpful start, as it would allow anyone to share them elsewhere, without needing to think too hard about how access to them is being managed. 

I was able to pull out the existing listing of events as an experiment by using the web inspector in my browser, but even doing this, I realise I have no URL to link to on the FOSDEM site, nor any shared ID (the url could possibly serve as this ID, but I don't know how often it might change)

https://gist.github.com/mrchrisadams/c4f7777bcf02c4d97837e47707ad8022

**Comment by mrchrisadams** [comment]
HAHAHAH! THIS IS AWESOME - this is such cool hack!

I love the use of GET params to list the bookmarked events like this- it's simple and effective, but also very clever and webby 💯 .

I'm very happy for this to be closed, as it lets me share a link for others to see the events I'm interested in, and decide to go or not. Bravo!

👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏
